/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'media',
  future: {
    hoverOnlyWhenSupported: true,
  },
  content: ['./index.html', './src/**/*.{vue,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Inter"', '"HarmonyOS Sans TC"', '"HarmonyOS Sans SC"', 'system-ui', 'sans-serif'],
        display: ['"Inter"', '"HarmonyOS Sans TC"', '"HarmonyOS Sans SC"', 'system-ui', 'sans-serif'],
        body: ['"Inter"', '"HarmonyOS Sans TC"', '"HarmonyOS Sans SC"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        ink: {
          50: 'rgb(var(--color-ink-50, 247 247 245) / <alpha-value>)',
          100: 'rgb(var(--color-ink-100, 239 239 234) / <alpha-value>)',
          200: 'rgb(var(--color-ink-200, 221 221 211) / <alpha-value>)',
          300: 'rgb(var(--color-ink-300, 198 198 184) / <alpha-value>)',
          400: 'rgb(var(--color-ink-400, 158 158 145) / <alpha-value>)',
          500: 'rgb(var(--color-ink-500, 119 119 108) / <alpha-value>)',
          600: 'rgb(var(--color-ink-600, 93 93 84) / <alpha-value>)',
          700: 'rgb(var(--color-ink-700, 67 67 61) / <alpha-value>)',
          800: 'rgb(var(--color-ink-800, 41 41 37) / <alpha-value>)',
          900: 'rgb(var(--color-ink-900, 23 23 21) / <alpha-value>)',
          950: 'rgb(var(--color-ink-950, 12 12 10) / <alpha-value>)',
        },
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
        outline: 'rgb(var(--color-outline) / <alpha-value>)',
        primary: 'rgb(var(--color-primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--color-primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--color-on-primary-container) / <alpha-value>)',
        secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
        'on-secondary': 'rgb(var(--color-on-secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--color-secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        error: 'rgb(var(--color-error) / <alpha-value>)',
        'on-error': 'rgb(var(--color-on-error) / <alpha-value>)',
        'error-container': 'rgb(var(--color-error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--color-on-error-container) / <alpha-value>)',
        warning: 'rgb(var(--color-warning) / <alpha-value>)',
        'warning-container': 'rgb(var(--color-warning-container) / <alpha-value>)',
        'on-warning-container': 'rgb(var(--color-on-warning-container) / <alpha-value>)',
      },
      boxShadow: {
        note: '0 18px 40px -24px rgba(17, 17, 17, 0.4)',
        elevated: '0 18px 40px -22px rgb(var(--color-shadow) / 0.34)',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
